version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 on the container
    volumes:
      - ./html:/usr/share/nginx/html  # Sync local files with container for live development
